name: Bug
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: ["connellboyce/12"]
body:
 - type: markdown
   attributes:
    value: |
     Thanks for taking the time to fill out this bug report.
 - type: input
   id: contact
   attributes:
    label: Contact Information
    description: Please provide your contact information (email, GitHub username, etc.) so I can reach you if needed.
    placeholder: example@email.com
   validations:
    required: false
 - type: textarea
   id: expected-behavior
   attributes:
    label: What is the expected behavior?
    description: Describe the expected behavior.
    placeholder: The bug doesn't happen!
   validations:
    required: true
 - type: textarea
   id: actual-behavior
   attributes:
    label: What is the actual behavior?
    description: Describe the actual behavior.
    placeholder: The bug happens!
   validations:
    required: true
 - type: textarea
   id: replication-steps
   attributes:
    label: How can I replicate this behavior?
    description: Give detailed instructions on how to replicate the bug.
    placeholder: First I do this, then I do that, and then I see the bug!
   validations:
    required: true
 - type: dropdown
   id: device-info
   attributes:
    label: What OS and browsers are you seeing the problem on?
    multiple: true
    options:
     - Windows
     - macOS
     - Linux
     - Firefox
     - Chrome
     - Safari
     - Microsoft Edge
     - Opera
     - Internet Explorer
 - type: textarea
   id: versions
   attributes:
    label: What versions of the OS and browsers are you seeing the issue on?
    description: If applicable...
    placeholder: macOS 14.0, Chrome 90.0
   validations:
    required: false
 - type: checkboxes
   id: terms
   attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow this project's [Code of Conduct](https://example.com).
    options:
     - label: I agree to follow this project's Code of Conduct
       required: true