name: Vulnerability
description: File a security vulnerability.
title: "[Vulnerability]: "
labels: ["vulnerability"]
projects: ["connellboyce/12"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this security vulnerability report.
  - type: input
    id: contact
    attributes:
      label: Contact Information
      description: Please provide your contact information (email, GitHub username, etc.) so I can reach you if needed.
      placeholder: example@email.com
    validations:
      required: false
  - type: textarea
    id: vulnerability-info
    attributes:
      label: What is the vulnerability?
      description: Describe the details of the vulnerabilities you found, including any steps to reproduce the issue. List any potential impact or risks associated with the vulnerability. Provide your device and OS information if relevant.
      placeholder: Tell me what you see!
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow this project's [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true